#!/usr/bin/env python3
"""The attack briefing's "Already known" list, measured instead of remembered.

    python3 scripts/build-attack-facts.py

WHY THIS EXISTS

Attack 3 ran with the Attack 1 version of this list still in place: "4 roles have no
path", "0 of 353 are reviewed", "171 of 353 have no publish date". A designer checked,
found seven paths, and reported the briefing itself as stale. An attacker correcting its
own instructions is the method working and the plan failing.

The list said it was refreshed every round. It was refreshed by remembering to refresh
it, which is not a mechanism. Now the numbered half is written from the same measurement
that writes docs/STATUS.md, on every build, and a round that forgets cannot happen.

The other half - the facts with no number in them - stays written out below. It is
short, it changes when a decision changes rather than when the data moves, and no
measurement can produce it.
"""
import importlib.util
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FACTS = os.path.join(ROOT, "docs", "attack", "00-facts.md")
START = "<!-- ALREADY-KNOWN:start  generated by scripts/build-attack-facts.py -->"
END = "<!-- ALREADY-KNOWN:end -->"

# Everything that changes when a decision changes rather than when the data moves.
# Anything with a number in it belongs above, not here.
SETTLED = [
    "**The report link needs a GitHub account.** Most of the audience does not have one.",
    "**Some hosts refuse automated checking**, so their links are confirmed by a person "
    "or not at all.",
    "**No analytics, no tracking, no accounts.** By design, and not an oversight.",
]


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def pct(a, b):
    return int(round(100.0 * a / b)) if b else 0


def cells_phrase(keys):
    """Cell names from the measurement, never typed."""
    return ", ".join("`%s`" % k for k in keys)


def bullets(m):
    n = m["resources"]
    out = []

    reviewed = m["tier"].get("reviewed", 0)
    out.append("**Nothing is `reviewed`.** %d of %d rows carry the top badge. It is empty "
               "by design and only a person can change it." % (reviewed, n)
               if not reviewed else
               "**%d of %d rows are `reviewed`.** A person has read those end to end."
               % (reviewed, n))

    out.append("**Most of the catalogue is Anthropic's own material** — %d of %d, %d%% — "
               "and `how-we-check.html` says so."
               % (m["official"], n, pct(m["official"], n)))

    out.append("**%d%% of cards say “No publish date given”** (%d of %d). That "
               "went up on purpose: every stored date was checked against its own page "
               "and any that could not be traced was cleared."
               % (pct(m["unverified"], n), m["unverified"], n))

    if m["empty_cells"]:
        out.append("**%s %s empty.** A reader who answers both front-door questions that "
                   "way is told we have nothing."
                   % (cells_phrase(m["empty_cells"]),
                      "is" if len(m["empty_cells"]) == 1 else "are"))
    for key, count, _pubs in m["zero_non_anthropic"]:
        out.append("**`%s` has nothing independent** — all %d of its candidates are "
                   "Anthropic's own." % (key, count))

    covered, roles = paths_covered()
    out.append("**Every one of the %d roles has a path** (%d paths, %d steps)."
               % (roles, m["paths"], m["path_steps"]) if covered == roles else
               "**%d of the %d roles have a path** (%d paths, %d steps). A role with no "
               "path is a gap we know about."
               % (covered, roles, m["paths"], m["path_steps"]))

    return out + SETTLED


def paths_covered():
    """How many roles a path reaches, and how many there are."""
    import json
    paths = json.load(io.open(os.path.join(ROOT, "data", "paths.json"), encoding="utf-8"))
    pc = load("pick_candidates", os.path.join(ROOT, "scripts", "pick-candidates.py"))
    reached = set()
    for p in paths:
        reached.update(p.get("roles") or [])
    return len(reached & set(pc.ROLES)), len(pc.ROLES)


def main():
    measure = load("measure", os.path.join(ROOT, "scripts", "measure.py"))
    m = measure.measure()

    body = ["", "An agent may sharpen or contradict these. It earns nothing by "
                "rediscovering them.", "",
            "*Measured %s, on the same run that writes `docs/STATUS.md`.*" % m["generated"],
            ""]
    body += ["- " + b for b in bullets(m)]
    body.append("")

    text = io.open(FACTS, encoding="utf-8").read()
    if START not in text or END not in text:
        sys.exit("%s has no ALREADY-KNOWN markers — add them around the list first."
                 % os.path.relpath(FACTS, ROOT))
    new = re.sub(re.escape(START) + r".*?" + re.escape(END),
                 START + "\n".join(body) + END, text, count=1, flags=re.S)
    io.open(FACTS, "w", encoding="utf-8", newline="\n").write(new)
    print("  docs/attack/00-facts.md  “Already known” written from the "
          "measurement, %s" % m["generated"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
