#!/usr/bin/env python3
"""
Wrap the JSON data files as plain JavaScript so the site opens from a folder.

Browsers block fetch() on file:// URLs. A static site that fetches its own data
therefore shows a blank page when you double-click index.html — it only works behind a
web server. That is a bad deal for a site whose whole content is three data files: it
means nobody can look at their own copy without knowing what a local server is.

Loading the same data through a <script> tag has no such restriction, so the site works
identically from the filesystem and from a host, with no fetch and no CORS anywhere.

The JSON files stay the source of truth. This only mirrors them.

    python3 scripts/build-data-js.py

Run it after anything that edits data/*.json. build-all.sh does this for you.
"""

import json
import os

PAIRS = [
    ("data/items.json",           "data/items.js",           "LC_ITEMS"),
    ("data/paths.json",           "data/paths.js",           "LC_PATHS"),
    ("data/search-keywords.json", "data/search-keywords.js", "LC_SEARCH_INDEX"),
]

HEADER = ("/* GENERATED by scripts/build-data-js.py — do not edit.\n"
          "   Source of truth is {src}. Regenerate after changing it. */\n")


def main():
    for src, dst, var in PAIRS:
        if not os.path.exists(src):
            print(f"  {src} missing — skipped")
            continue
        data = json.load(open(src, encoding="utf-8"))
        with open(dst, "w", encoding="utf-8") as f:
            f.write(HEADER.format(src=src))
            f.write(f"window.{var} = ")
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
            f.write(";\n")
        n = len(data) if isinstance(data, list) else len(data.get("ids", []))
        print(f"  {dst:28} {os.path.getsize(dst)//1024:4} KB  ({n} records)")


if __name__ == "__main__":
    main()
