#!/usr/bin/env python3
"""
Wrap the JSON data files as plain JavaScript so the site opens from a folder.

Browsers block fetch() on file:// URLs. A static site that fetches its own data
therefore shows a blank page when you double-click index.html — it only works behind a
web server. That is a bad deal for a site whose whole content is three data files: it
means nobody can look at their own copy without knowing what a local server is.

Loading the same data through a <script> tag has no such restriction, so the site works
identically from the filesystem and from a host, with no fetch and no CORS anywhere.

The JSON files stay the source of truth. This only mirrors them.

    python3 scripts/build-data-js.py

Run it after anything that edits data/*.json. build-all.sh does this for you.
"""

import json
import os

# Fields no JavaScript on the site reads. Measured 2026-08-27 by grepping assets/js for
# every key in items.json: these seven are 192 KB of the 610 KB every visitor downloads,
# and nothing renders one of them.
#
# They are stripped from the mirror, not from data/items.json. The question was "render
# `notes` or stop shipping it", and the answer is stop shipping it, because `notes` is an
# editorial working field written in an internal voice - "CAUTION:", "Merged 2026-08-27
# with the anthropic.skilljar.com row". Putting that on the page would publish our
# workings. It is also how an unsourced allegation about a named person reached the live
# site: it sat in `notes` and `skip_if` and was shipped to every browser while nobody
# considered it published. Reader-facing facts that are currently buried in `notes` -
# prices above all - deserve real fields of their own, deliberately, and that is a
# content decision rather than a dump.
#
# `keywords` and `questions` are the search index's raw material and already ship,
# built, in data/search-keywords.js. They were being sent twice.
STRIP_FROM_MIRROR = ("notes", "keywords", "questions", "alt_skip_if",
                     "language", "review_note", "field")

PAIRS = [
    ("data/items.json",           "data/items.js",           "LC_ITEMS"),
    ("data/paths.json",           "data/paths.js",           "LC_PATHS"),
    ("data/search-keywords.json", "data/search-keywords.js", "LC_SEARCH_INDEX"),
    ("data/publisher-marks.json", "data/publisher-marks.js", "LC_PUBLISHER_MARKS"),
    ("data/picks.json",           "data/picks.js",           "LC_PICKS"),
]

HEADER = ("/* GENERATED by scripts/build-data-js.py — do not edit.\n"
          "   Source of truth is {src}. Regenerate after changing it. */\n")


def main():
    for src, dst, var in PAIRS:
        if not os.path.exists(src):
            print(f"  {src} missing — skipped")
            continue
        data = json.load(open(src, encoding="utf-8"))
        if src.endswith("items.json"):
            data = [{k: v for k, v in row.items() if k not in STRIP_FROM_MIRROR}
                    for row in data]
        if src.endswith("picks.json"):
            # The runners-up, subjects, notes and fingerprints are the audit record -
            # "stored, not displayed" is the spec's own wording - and they live in
            # data/picks.json in the repository. The browser gets only what the picks
            # block renders. Same reasoning as STRIP_FROM_MIRROR above: shipping our
            # workings to every reader is publishing them.
            # two_pick_cause crosses because D7 makes the block SAY why it is thin,
            # and the sentence is keyed on the cause the validator already enforces.
            # A cause invented in the browser could drift from the one in the file; a
            # cause carried across cannot.
            data = {"cells": {
                key: {"picked_by": c.get("picked_by"),
                      "picked_on": c.get("picked_on"),
                      "two_pick_cause": c.get("two_pick_cause"),
                      "picks": [{"url": q["url"], "reason": q["reason"]}
                                for q in c.get("picks", [])]}
                for key, c in (data.get("cells") or {}).items()}}
        with open(dst, "w", encoding="utf-8") as f:
            f.write(HEADER.format(src=src))
            f.write(f"window.{var} = ")
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
            f.write(";\n")
        if isinstance(data, list):
            n = len(data)
        elif "ids" in data:
            n = len(data["ids"])          # search-keywords.json's shape
        elif "cells" in data:
            n = len(data["cells"])        # picks.json's shape
        else:
            n = len(data)                 # a flat map, e.g. publisher-marks.json
        print(f"  {dst:28} {os.path.getsize(dst)//1024:4} KB  ({n} records)")


if __name__ == "__main__":
    main()
