#!/usr/bin/env python3
"""
Install the git hooks. Run once per clone.

    python3 scripts/install-hooks.py

Writes a two-line .git/hooks/pre-commit that calls scripts/pre-commit.py. The logic
stays in the repository rather than in .git/, because a hook inside .git/ is invisible
to review, never diffed, and does not exist at all on a fresh clone - which is exactly
the shape of a guard nobody can tell is missing.
"""

import os
import stat
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HOOK = os.path.join(ROOT, ".git", "hooks", "pre-commit")

BODY = """#!/bin/sh
# Generated by scripts/install-hooks.py - do not edit here, edit scripts/pre-commit.py.
#
# Each candidate is TESTED, not merely located. Windows ships an App Execution Alias
# named `python3` that is not Python - it prints "Python was not found..." and exits
# non-zero - so `command -v python3` succeeds and running it fails. This hook blocked
# its own commit twice before that distinction was drawn.
ROOT="$(git rev-parse --show-toplevel)"
for PY in python3 python py; do
  if "$PY" -c "import sys" >/dev/null 2>&1; then
    exec "$PY" "$ROOT/scripts/pre-commit.py"
  fi
done
echo "pre-commit: no working python interpreter (tried python3, python, py)." >&2
echo "Install one, or remove .git/hooks/pre-commit to skip this check." >&2
exit 1
"""


def main():
    hooks = os.path.dirname(HOOK)
    if not os.path.isdir(hooks):
        sys.exit("no .git/hooks directory - run this from inside a clone")
    with open(HOOK, "w", encoding="utf-8", newline="\n") as f:
        f.write(BODY)
    os.chmod(HOOK, os.stat(HOOK).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    print("installed .git/hooks/pre-commit -> scripts/pre-commit.py")
    print("it rejects control characters in tracked text and runs the catalogue "
          "validator")
    return 0


if __name__ == "__main__":
    sys.exit(main())
