#!/usr/bin/env python3
"""
Measure the Anthropic Academy use-case gallery's weight in the catalogue.

    python3 scripts/measure-use-cases.py            # the numbers
    python3 scripts/measure-use-cases.py --markdown # the report, for docs/

D12 is a spec, not a ruling. The developer agent in Attack 2 counted 148 rows harvested
from one prompt-recipe gallery, 78 of them filed at "built things with it", and made the
argument in one line: a prompt recipe is not building. That may be right and it is not
mine to decide, so this round measures and stops.

Three questions, and nothing else:

  1. How many are there, and where do they sit?
  2. How many did the editorial layer actually choose - picks and path steps?
  3. What does every `builder` cell look like without them?

The third is the one that decides it. If a level empties when they go, they are holding
the level up and removing them is a different job from removing them.
"""

import io
import json
import os
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREFIX = "https://academy.claude.com/use-cases/"
LEVELS = ["never-used", "basic", "confident", "builder"]


def load(name):
    with io.open(os.path.join(ROOT, "data", name), encoding="utf-8") as f:
        return json.load(f)


def main():
    items = load("items.json")
    picks = load("picks.json")["cells"]
    paths = load("paths.json")
    paths = paths if isinstance(paths, list) else paths.get("paths", [])

    gallery = [x for x in items if x["url"].startswith(PREFIX)]
    gurls = {x["url"] for x in gallery}
    roles = sorted({r for x in items for r in (x.get("roles") or [])})

    picked = {p["url"] for c in picks.values() for p in c["picks"]}
    runners = {r["url"] for c in picks.values() for r in c.get("runners_up", [])}
    steps = {s["url"] for p in paths for s in p.get("steps", [])}

    md = "--markdown" in sys.argv
    out = []

    def say(s=""):
        out.append(s)

    say("# D12 measurement - the use-case gallery")
    say()
    say("Generated by `scripts/measure-use-cases.py`. Nothing here is typed.")
    say()
    say("## 1. How many, and where")
    say()
    say("**%d of %d rows (%.0f%%)** come from `%s`."
        % (len(gallery), len(items), 100.0 * len(gallery) / len(items), PREFIX))
    say()
    lev = Counter(x["level"] for x in gallery)
    tim = Counter(x["time"] for x in gallery)
    tie = Counter(x["tier"] for x in gallery)
    say("| level | gallery rows | all rows at that level | gallery share |")
    say("|---|---|---|---|")
    for L in LEVELS:
        total = sum(1 for x in items if x["level"] == L)
        say("| %s | %d | %d | %.0f%% |"
            % (L, lev[L], total, 100.0 * lev[L] / total if total else 0))
    say()
    say("Time buckets: %s" % ", ".join("%s %d" % (k, v) for k, v in tim.most_common()))
    say("Tiers: %s" % ", ".join("%s %d" % (k, v) for k, v in tie.most_common()))
    say()

    say("## 2. What the editorial layer chose")
    say()
    gp = gurls & picked
    gr = gurls & runners
    gs = gurls & steps
    say("- **picks:** %d of the %d gallery rows are picked somewhere. "
        "%d distinct resources are picked across the %d cells - a few are picked in "
        "more than one." % (len(gp), len(gallery), len(picked), len(picks)))
    say("- **runners-up:** %d are recorded as a runner-up" % len(gr))
    say("- **path steps:** %d of %d path steps come from the gallery"
        % (len(gs), len(steps)))
    say()
    if gp:
        say("The picked ones:")
        say()
        for u in sorted(gp):
            it = next(x for x in items if x["url"] == u)
            where = [k for k, c in picks.items()
                     if any(p["url"] == u for p in c["picks"])]
            say("- `%s` %s - %s" % (it["level"], it["title"][:56], ", ".join(where)))
        say()

    say("## 3. Every `builder` cell without them")
    say()
    say("The count a reader would see, and the count they would see if the gallery were "
        "not in the catalogue. `picks` is how many of that cell's picks are gallery rows.")
    say()
    say("| cell | now | without | lost | picks from the gallery |")
    say("|---|---|---|---|---|")
    emptied, thinned = [], []
    for r in roles:
        now = [x for x in items if r in (x.get("roles") or []) and x["level"] == "builder"]
        without = [x for x in now if x["url"] not in gurls]
        key = "%s|builder" % r
        cell = picks.get(key)
        pg = (sum(1 for p in cell["picks"] if p["url"] in gurls) if cell else 0)
        pn = (len(cell["picks"]) if cell else 0)
        say("| %s | %d | %d | %d | %d of %d |"
            % (key, len(now), len(without), len(now) - len(without), pg, pn))
        if now and not without:
            emptied.append(key)
        elif len(without) < 5 and now:
            thinned.append((key, len(now), len(without)))
    say()
    if emptied:
        say("**Cells that empty completely:** %s" % ", ".join("`%s`" % k for k in emptied))
    if thinned:
        say("**Cells that fall under five:** %s"
            % ", ".join("`%s` %d to %d" % t for t in thinned))
    say()

    say("## 4. What a gallery row looks like")
    say()
    say("Three at random from the `builder` level, so the argument can be judged against "
        "the thing itself rather than against a description of it.")
    say()
    b = [x for x in gallery if x["level"] == "builder"]
    for x in b[:3]:
        say("- **%s** - %s, %s" % (x["title"], x["time"], x["tier"]))
        say("  - *For:* %s" % (x.get("who_for") or "")[:150])
        say("  - *Skip if:* %s" % (x.get("skip_if") or "")[:150])
    say()

    text = "\n".join(out)
    if md:
        dst = os.path.join(ROOT, "docs", "attack", "2", "D12-MEASUREMENT.md")
        with io.open(dst, "w", encoding="utf-8", newline="\n") as f:
            f.write(text + "\n")
        print("wrote %s" % dst)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
